### ISSUE TITLE
'test_load_urdf.py' won't work

### ISSUE THREAD

**Issue by Learner209** [mvig-robotflow/pyrfuniverse#5]
Hi! I have been trying to run 'Test/test_load_urdf.py' but the following error keeps showing up: 
![](https://notes.sjtu.edu.cn/uploads/upload_7bd70118e5e129a807a4297786652bfc.png)

![](https://notes.sjtu.edu.cn/uploads/upload_1685d4e1daa934b3ac659c9094d365d8.png)

The rfuniverse window immediately shuts down then. However, there are few times that I suceessfully lauched the script.
I have tried in version '0.8.3' and '0.8.4' and the error is the same, i have ensured that the version of `pyrfuniverse` and `rfuniverse` is the same, maybe is there anything that i miss?

**Comment by ghzh26252** [comment]
This issue is caused by Pycharm or VSCode automatically adding the source code of "pyrfuniverse" from the relative path to the environment path, which prevents the Python script from importing the modules installed by pip.

However, I have discovered a new exception while testing on Ubuntu 22.04 system, and I will provide the fix here:
If you run "test_load_urdf.py" without any error but the UR5 robotic arm does not appear in the scene, it means there is an exception present.
This exception occurs when the URDF includes `.dae` model file. Here's how to fix it:

1. Add a link to the "libdl.so" library: 
`sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so`
2. Install the "libminizip1" module: 
[libminizip1](https://packages.ubuntu.com/jammy/libminizip1)
